#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json5
import json
import sys

if __name__ == '__main__':
    args = sys.argv
    filename = args[1]
    with open(filename, "r") as fp:
        json_map = json5.load(fp)

    s = json.dumps(json_map, separators=(',', ':'), indent=4, ensure_ascii=False)
    with open(filename, "w") as fp:
        fp.write(s)
